Update session-utils.ts
I'm getting the following error when I use Shopify.Session.RedisSessionStorage.

TypeError: entries.filter is not a function
@shopify/shopify-api/dist/auth/session/session-utils.js:11:10

I made the above changes work perfectly. Please fix it, and; let me know the reason.